### ISSUE TITLE
For Clover Bootloader users and change Wifi connection without restart your Mac 

### ISSUE THREAD

**Issue by lzhoang2601** [chris1111/D-LinkUtility-Package#1]
[RT2870_Installer.zip](https://github.com/chris1111/D-LinkUtility-Package/files/6760062/RT2870_Installer.zip)

Function:
1. Install/uninstall kext and utility
2. Change Wifi Connection

Install: Run install.command -> press password -> pick option 1 -> press SSID and SSID Password -> Restart. Done
Uninstall: Run install.command -> press password -> pick option 1 -> Restart. Done

Note:
1. Bug add login item MiniTaskUSB-DWA160
2. RT2870USBWirelessDriver.kext used is changed for Mi Portable Wifi (MT7601), not sure full support like chris1111's kext
3. With OpenCore users, need add kext to config manually
4. Script will not be updated in the future

**Comment by chris1111** [comment]
You are not use the latest update kext
