### ISSUE TITLE
Is there any plan to support mt7612u?

### ISSUE THREAD

**Issue by gushengyuan** [chris1111/D-LinkUtility-Package#10]
Hi @chris1111 ,

Is there any plan to support mt7612u?
I think the mt7612u chip based devices are almost the most popular dual-band usb wireless devices for mediatek.

**Comment by chris1111** [comment]
mt7612u is already on, its part of [MT7601](https://www.mediatek.com/products/broadband-wifi/mt7612u)

I will add to description soon
