### ISSUE TITLE
Wifi-Utility not launching

### ISSUE THREAD

**Issue by vectorseven** [chris1111/D-LinkUtility-Package#11]
Hi. im having trouble to make my USB wifi work. 

My specs: 
- Hackintosh OC Big Sur 11.6.6
- DWA-125 rev A2 (Fully working in Win11, was working well under Catalina some months ago)

Problems:
- After installing kext --> DWA-125 light on
- OS Menu: NO Connection!! --> Clicking Wireless Preference does nothing -> after rebooting no changes.
- Try to launch the app from terminal looking for errors -> nothing. (Does it have a verbose mode option?)

Note: I have used your kexts before when I was in Catalina/High Sierra? (can't remember this last well) and it worked there (It recognizes the USB and could connect properly aside from the low download speed I still consider it a working wifi). 
My little understanding is that the kext is not recognizing my USB anymore so that's the reason the app doesn't launch. There were any changes in the kext in this new version for Big Sur or DWA-125 is not supported anymore?

Thanks for your help and your work.

**Comment by chris1111** [comment]
DWA-125 rev A
Only work in Windows
https://support.dlink.ca/ProductInfo.aspx?m=DWA-125

![Screen Shot 2022-05-26 at 7 28 05 PM](https://user-images.githubusercontent.com/6248794/170595522-a315b747-4816-4d94-8aba-c09db33a58b2.png)

**Comment by vectorseven** [comment]
I appreciate you answer,

just to say this USB model WAS working fine with Catalina, so maybe there was some kind of change in the kext or the wifi Utility (tried the old Catalina Panel but no avail)

I do understand, however, it's a matter of D-LINK to give updated drivers. 

Thanks, anyway.
