### ISSUE TITLE
ryzentosh

### ISSUE THREAD

**Issue by eymenhudaua** [chris1111/D-LinkUtility-Package#12]
I am using ryzen 5 3600, when I click on no connection and click on wireless preference, the utility does not open. i m using ralink rt3070 chip

**Comment by chris1111** [comment]
ralink rt3070 is support 
Check your config something wrong?

**Comment by eymenhudaua** [comment]
let me send you my efi file. https://transfer.sh/nWI919/Ryzentosh_R53600_RX550.zip

**Comment by eymenhudaua** [comment]
i checked, i don't see any problem. what do you think could be the problem?

**Comment by chris1111** [comment]
do you use OC or Clover or /Library/Extensions?

**Comment by eymenhudaua** [comment]
opencore

**Comment by chris1111** [comment]
Go to HOME/Library/Preferences
send me in ZIP
**ActiveProfileSetting.plist
AdvancedProfileSetting.plist**

**Comment by eymenhudaua** [comment]
there is no such plist in that directory

**Comment by eymenhudaua** [comment]
![Ekran Resmi 2022-06-21 14 47 26](https://user-images.githubusercontent.com/67499317/174791979-af4204e9-b189-492b-82b0-1cf06029e315.png)

**Comment by chris1111** [comment]
I told your u this is not the he good Library

**Comment by eymenhudaua** [comment]
what should I do?

**Comment by eymenhudaua** [comment]
> I told you this is not the good Library
> […](#)
> Sent from my iPhone
> On Jun 21, 2022, at 7:48 AM, skrrthanze ***@***.***> wrote: ﻿ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

hey chris, my situation is urgent. what should I do?

**Comment by chris1111** [comment]
this
[
](https://github.com/chris1111/D-LinkUtility-Package/issues/12#issuecomment-1161028793)

**Comment by chris1111** [comment]
If you don't send me the requested files, I can't help you.
