### ISSUE TITLE
d-link in panel disappears after couple of seconds of launch.

### ISSUE THREAD

**Issue by raulsaeed** [chris1111/D-LinkUtility-Package#15]
hello I have macOS 12 installed on my laptop and I bought a card for it it is a mediatek mt7601 card and I installed your d-link util and typed every thing right but after restart your util in the panel disappears after couple of seconds of launch and cannot connect to internet and I try to launch the d-link app again but it is gone again after couple go seconds

**Comment by chris1111** [comment]
This utility has no panel, which panel are you talking about?

**Comment by raulsaeed** [comment]
Uploading 70928434690__8C3386B0-0D34-41B1-886A-466C5A5A848F.MOV…

**Comment by raulsaeed** [comment]
i have
network card : mt7603,mt7601
and a ralink 5370 non work

**Comment by chris1111** [comment]
no movie here
