### ISSUE TITLE
d-link util not working 

### ISSUE THREAD

**Issue by raulsaeed** [chris1111/D-LinkUtility-Package#16]
https://github.com/chris1111/D-LinkUtility-Package/assets/64417577/14889b68-d6d8-485a-9696-57e3e2456af0

**Comment by raulsaeed** [comment]
i have 
network card : mt7603,mt7601
and a ralink 5370 non work

![Uploading image.jpg…]()

**Comment by chris1111** [comment]
If the Status Bar App disapears like in your Video its probably you have not setup the connection with PlistEdit App

**Comment by raulsaeed** [comment]
yes i did and i did not spell anything wrong in the plist

**Comment by chris1111** [comment]
Send my the file in /$HOME/Library/Preferences/`ActiveProfileSetting.plist`

This Library is hidden in HOME
put the file here on ZIP

**Comment by raulsaeed** [comment]
hello sorry for being late i looked around the /$Home/Library/Preferences/ directory i found nothing with that name but now the app does not exit because i got a new mt7601 but the d-link App says [No Connection!!]

**Comment by raulsaeed** [comment]
if you could help me with a fix to my card that i would be very thank full i want to get to know xcode and objective-c lang and i can't afford a real mac this hackintosh is my only option .

**Comment by chris1111** [comment]
I told you /$Home/Library/Preferences/

This Library is Hidden in Home directory, you need to show all files to see this Library

**Comment by raulsaeed** [comment]
> I told you /$Home/Library/Preferences/
> 
> This Library is Hidden in Home directory, you need to show all files to see this Library

![Uploading image.jpg…]()

**Comment by raulsaeed** [comment]
yes i did even i terminal i did a ls -al command nothing whit that name

**Comment by chris1111** [comment]
Impossible

**Comment by raulsaeed** [comment]
let me try reinstall again i don't know

**Comment by raulsaeed** [comment]
ok know i have it let me boot into windows so i can send it to you

**Comment by raulsaeed** [comment]
[ActiveProfileSetting.plist.zip](https://github.com/chris1111/D-LinkUtility-Package/files/11857928/ActiveProfileSetting.plist.zip)

**Comment by chris1111** [comment]
looks ok

**Comment by raulsaeed** [comment]
is there any thing you could do to fix my problem i really would be thankful.

**Comment by chris1111** [comment]
Whats is the macOS version you try? 
You can try changing USB port

**Comment by raulsaeed** [comment]
im on macos monterey and of course i tried changing ports and also i changed 3 adapters

**Comment by chris1111** [comment]
I have 3 adapter working without issue

**Comment by chris1111** [comment]
maybe try changing MAC Address

```
<key>BSSID</key>
<string>8cdcd4d68647</string>
```

**Comment by raulsaeed** [comment]
[Uploading image.jpg…]

**Comment by raulsaeed** [comment]
https://github.com/chris1111/D-LinkUtility-Package/assets/64417577/a59a9949-ac46-49b6-9f43-bd3d601c2ced

**Comment by raulsaeed** [comment]
now the file is gone again after a reboot and the wlan 802.11 shows up in settings but can't be turned on .

**Comment by chris1111** [comment]
Take a look `TP Link Archer T2UH` in macOS Sonoma 14 using OpenCore Package install


https://github.com/chris1111/D-LinkUtility-Package/assets/6248794/96d3eb75-06f9-4f2e-98c1-105558176177

**Comment by raulsaeed** [comment]
https://github.com/chris1111/D-LinkUtility-Package/assets/64417577/811407fd-6ede-4eac-bb88-535650f8bd38

**Comment by raulsaeed** [comment]
I even installed the d-link package to OpenCore and reboot
in the setting there is plan 802.11 ethernet being made for the d-link util but,
the d-link util does not pick it up and crashes .

**Comment by chris1111** [comment]
Your not looking in the good Library
I've told you this several times

![Screenshot 2023-06-25 at 08 05 24](https://github.com/chris1111/D-LinkUtility-Package/assets/6248794/4d4f5438-e4d8-44da-9efd-b7553f48cb83)

**Comment by raulsaeed** [comment]
im really sorry but isn't what you want is /home/library/prefeences

**Comment by chris1111** [comment]
Anyway issue is closed, it is obvious that you are not using it in the right way after all that I have observed

**Comment by raulsaeed** [comment]
Not really the case i looked in to the directory you said but fine thats ok .

**Comment by chris1111** [comment]
ok one last thing I'm doing to try to help you because your subject seems quite confusing so use this PlisEdit

[PlistEdit.zip](https://github.com/chris1111/D-LinkUtility-Package/files/11859727/PlistEdit.zip)

**Comment by raulsaeed** [comment]
asks for mac address what i type mac address for router?

**Comment by chris1111** [comment]
Try to use the same as Ethernet
MAC Address without colon
![Screenshot 2023-06-25 at 08 54 57](https://github.com/chris1111/D-LinkUtility-Package/assets/6248794/72143282-c4fb-45cf-8f69-04f36c00cc1b)

See infos without colon
Result
`ecb1d72d860`

**Comment by raulsaeed** [comment]
ok

**Comment by chris1111** [comment]
After enter infos, make sur USB adapter is plug in then open the App Wifi-Utility in Applications

**Comment by raulsaeed** [comment]
https://github.com/chris1111/D-LinkUtility-Package/assets/64417577/4660f7b5-0376-4183-9c2f-13fa0c9e3bc1

**Comment by chris1111** [comment]
what is this video doing


NOTHINGS man again

**Comment by raulsaeed** [comment]
i put the info in like you said and i just wanted to show that everything is fine in the active.plist in the video but the app does not open

**Comment by chris1111** [comment]
Video show nothing about WIFI
Video show nothing about wifi

This is the MAC adress you need to enter in the PlisEdit with the rest of the other correct Infos

`8cdcd4d68647`

**Comment by raulsaeed** [comment]
in the video you can see the MAC is changed the usb wifi card is connected like you said but not working

**Comment by chris1111** [comment]
> in the video you can see the MAC is changed the usb wifi card is connected like you said but not working


Video show nothing about WIFI


This is the MAC adress you need to enter in the PlisEdit with the rest of the other correct Infos

`8cdcd4d68647`

**Comment by chris1111** [comment]
All of your video as no sense

**Comment by chris1111** [comment]
`Wifi name` is the `Rooter Name `because your not have a native wifi

Pasword is `Rooter pasword`

**Comment by raulsaeed** [comment]
just listen to me and tell me what i did wrong.
- installed d-link util and chose install /Library/Extensions
- i typed my password in settings and activated mediatek 
- typed my router ssid and wpa password 
- after the app installed perfectly i quit and reboot
- after reboot nothing works man.
im really hare for help

**Comment by raulsaeed** [comment]
> PlistEdit.zip

and for this i 
1-typed the ethernet mac to plist app and 
2- typed router ssid
3-typed the wpa password of router 



then i sent this video after i did the plist app and still not working.

**Comment by chris1111** [comment]
> just listen to me and tell me what i did wrong.
> 
> * installed d-link util and chose install /Library/Extensions
> * i typed my password in settings and activated mediatek
> * typed my router ssid and wpa password
> * after the app installed perfectly i quit and reboot
> * after reboot nothing works man.
>   im really hare for help

Ha yea because you told me Installing [from OpenCore ](https://github.com/chris1111/D-LinkUtility-Package/issues/16#issuecomment-1605917741)

So what is true and what is false

Issue will be deleted
