### ISSUE TITLE
Add support for MEDIATEK Corp. MT7922 802.11ax PCI Express Wireless Network Adapter

### ISSUE THREAD

**Issue by amontalban** [chris1111/D-LinkUtility-Package#17]
Hi @chris1111,

Thank you for creating this tool, I tried it with my MT7922 but didn't work.

Do you know if it would be possible to support this model of Mediatek? Looks like Linux supports it but I don't know anything about macOS drivers.

Thank you once again!

**Comment by chris1111** [comment]
Thanks @amontalban  but there is no source for this macOS drivers, I can not add support for other drivers to this utility
