### ISSUE TITLE
PlistEdit cannot add Wifi with spaces

### ISSUE THREAD

**Issue by ebcoelho** [chris1111/D-LinkUtility-Package#19]
I'm trying to manage the Wifi Network of Hotel with SSID "Plaza Francia" but PlistEdit returns the error below:

![image](https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/537c9b09-63a3-4fd9-94b7-a46c56ef8401)
![image](https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/7efe95f5-88f2-48ef-a595-6a8e048beb0e)
![image](https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/5225d196-d44a-4d1b-af33-fa440b54d276)
![image](https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/d67f6ca9-4892-471a-8dab-4afa7c9a49cf)
<img width="375" alt="image" src="https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/2733793d-7e5d-417d-a9fd-39d550c12cd9">

**Comment by chris1111** [comment]
It look like connect anyway 😃

**Comment by ebcoelho** [comment]
> It look like connect anyway 😃

The screenshot below is from my internal wlan adapter, but as the signal is too low keeps disconnecting every minute. So my status now is the Alfa AWUS036ACHM does not works for this SSID with spaces...


![](https://user-images.githubusercontent.com/16887421/256072092-d67f6ca9-4892-471a-8dab-4afa7c9a49cf.png)

**Comment by chris1111** [comment]
Try this  [Troubleshoothing](https://github.com/chris1111/D-LinkUtility-Package/blob/main/Troubleshooting.md)

**Comment by ebcoelho** [comment]
> Try this [Troubleshoothing](https://github.com/chris1111/D-LinkUtility-Package/blob/main/Troubleshooting.md)

You have to try the PlistEdit.app with an SSID with " " spaces.. that's where I'm getting stuck 😢 

![image](https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/c875abd2-7dfb-4085-a667-b1e998075cd3)

![image](https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/10d89c29-43bc-4ff9-9401-b4a8649db872)

![image](https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/35a0d4b7-b189-498c-8a40-708d7c19727f)

![image](https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/ac2ad126-dba1-4d9e-8230-dc16f0e142e7)

**Comment by ebcoelho** [comment]
The driver it seems loaded because the led is green on wifi adapter, csrutil is disable and kext-consent ( /usr/sbin/spctl kext-consent add ZG5MN8MJ6A) done but the Consent.command is not running fine

<img width="1004" alt="image" src="https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/26e301da-f8fb-4fbc-a6a6-f44f50775308">

<img width="1143" alt="image" src="https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/17bc5fd3-4564-4ca3-aab1-01f34a40e6e8">


<img width="633" alt="image" src="https://github.com/chris1111/D-LinkUtility-Package/assets/16887421/0af458a7-5c43-4c5c-a1fa-8b493c73c025">

**Comment by chris1111** [comment]
Maybe in Catalina consent command is not the best from Apple
But in new macOS it work good

Try SIP Disable without the consent configuration
