### ISSUE TITLE
I have set to no password will it still work?

### ISSUE THREAD

**Issue by chumdoggin** [chris1111/D-LinkUtility-Package#20]
I used the plistedit app and after entering the mac address there is a message that says no file specified. I look at the file in private/tmp and I see a number 3 where it says type of authentication. Is there a number that tells open authentication?

**Comment by chris1111** [comment]
Impossible

**Comment by chumdoggin** [comment]
Does that mean there must be a password set for it to work?

**Comment by chris1111** [comment]
it means you don't follow the guide and your issue doesn't make sense

**Comment by chumdoggin** [comment]
I was following the guide and I got the device to be seen by the network pref as 802.11n wlan but says no connection.
followed the direction to do the plist app and worked ok. It still said no connection after I made a password for the ssid. 

I tried to disable the gatekeeper and got an error 66. Just now I mounted the volume as a snapshot, uninstalled, reinstalled then trying to save the snapshot, from the directions at Dortania, (doing big sur) I got a failure.

**Comment by chris1111** [comment]
If you use OCLP why you are not using the program of OpenCore option

**Comment by chumdoggin** [comment]
It is regular OC and I used the OC option...

**Comment by chris1111** [comment]
>  considering gatekeeper wont mount?

Gatekeeper wont mount? another things doesn't  not make sense!
