### ISSUE TITLE
Everest EWN-689N doesn't work on macOS Monterey 12.6

### ISSUE THREAD

**Issue by stereoDotLuigi** [chris1111/D-LinkUtility-Package#21]
When I installed a Ralink RT2870 driver on Windows for my adapter, it worked.
But in macOS Monterey 12.6, when I installed D-LinkUtility-Package, it's light is shining but macOS isn't connecting Wi-Fi with it. I typed my Wi-Fi network name and password correctly. Should I've typed the original Wi-Fi name and password or the current one?

**Comment by stereoDotLuigi** [comment]
@chris1111

**Comment by chris1111** [comment]
I have a RT2870  adapter then it work with out issue

**Comment by stereoDotLuigi** [comment]
That really didn't solve my problem. 😐

**Comment by chris1111** [comment]
So problem is maybe your adapter is not compatible after 10.10?

**Comment by chris1111** [comment]
What is your` ID Product` and `ID Vendor` 
see infos in About this Mac / USB

**Comment by chris1111** [comment]
Try changing this kext in EFI/OC/kexts
[RT2870USBWirelessDriver.kext.zip](https://github.com/chris1111/D-LinkUtility-Package/files/12238321/RT2870USBWirelessDriver.kext.zip)

**Comment by chris1111** [comment]
If the first one not work try this one

[RT2870USBWirelessDriver.kext.zip](https://github.com/chris1111/D-LinkUtility-Package/files/12238495/RT2870USBWirelessDriver.kext.zip)

**Comment by stereoDotLuigi** [comment]
Just got kernel panic with both.

**Comment by stereoDotLuigi** [comment]
Should I change it's place in config.plist? For now, it's at the bottom of all kexts.

**Comment by chris1111** [comment]
Not change order 
KP It is strange ?

**Comment by chris1111** [comment]
I will see when back home

**Comment by chris1111** [comment]
Show me a picture of your device  About this Mac / USB

**Comment by stereoDotLuigi** [comment]
There was no KP but it still didn't work.
Here is my USB list:

**Comment by chris1111** [comment]
try this

[RT2870USBWirelessDriver.kext.zip](https://github.com/chris1111/D-LinkUtility-Package/files/12244375/RT2870USBWirelessDriver.kext.zip)

**Comment by stereoDotLuigi** [comment]
Still didn't work. It says "No Connection" while adapter's light is on?
I typed my current network name and password. Did I made the setup wrong?
I think my adapter has Ralink RT2870 chipset because it's driver worked for my adapter.

**Comment by chris1111** [comment]
There's nothing else I can do

**Comment by stereoDotLuigi** [comment]
I guess I should buy a new adapter, that adapter was old.

**Comment by chris1111** [comment]
[This one](https://www.amazon.ca/Alfa-AWUS036ACM-Long-Range-Dual-Band-Wireless/dp/B073X6RL9D)
⬇︎
[is really good](https://user-images.githubusercontent.com/6248794/160301333-85e357d4-29ab-4520-b70f-970858cfec28.png)

**Comment by stereoDotLuigi** [comment]
Unfortunately, I live in Turkey.
I need to pay 1.890 Turkish liras to buy it. Hella expensive.
Thanks for trying to help though. Goodbye! 😊👍

**Comment by stereoDotLuigi** [comment]
I think to buy ASUS N10 NANO. Is it working?

**Comment by chris1111** [comment]
I have a cheap but good [TP Link  Archer T2 UH ](https://www.ebay.com/p/14028311240)

**Comment by chris1111** [comment]
But See this here [Realtek Adapter](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter)

[Archer T3U Plus](https://www.amazon.ca/-/fr/TP-Link-Adaptateur-AC1300-Archer-T3U/dp/B07P6N2TZH/ref=asc_df_B07P6N2TZH/?tag=cafrdeshadgo-20&linkCode=df0&hvadid=459642259426&hvpos=&hvnetw=g&hvrand=3009611276875140538&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9000467&hvtargid=pla-759718675360&psc=1)

**Comment by stereoDotLuigi** [comment]
Hmm, that's actually cheaper but it's still expensive.
If you have a cheaper one, please let me know. Otherwise, that's okay.

**Comment by chris1111** [comment]
> Hmm, that's actually cheaper but it's still expensive. If you have a cheaper one, please let me know. Otherwise, that's okay.

[TL WN722N-V2](https://www.amazon.ca/TP-Link-TL-WN722N-Wireless-Adapter-Detachable/dp/B002SZEOLG)
Its a Realtek adapter, I have also this one

**Comment by chris1111** [comment]
> I'm hesitate. I really want to buy from Turkey because that's where I live. Some people recommended ASUS USB N10-NANO or some Ugreen adapter.

You can search in turkey for the card
If people testing the ASUS USB N10-NANO and works good, gor for this

**Comment by stereoDotLuigi** [comment]
Yes, they are saying that ASUS USB N10-NANO works for them.
This is the product in ASUS' website: https://www.asus.com/tr/networking-iot-servers/adapters/all-series/usbn10_nano/
But some people said it doesn't work good if you're one room far from router.

**Comment by chris1111** [comment]
I have also this one available in Turkey
[
](https://www.ubuy.com.tr/en/product/3E4NC6-tp-link-ac600-usb-wifi-adapter-for-pc-archer-t2u-plus-wireless-network-adapter-for-desktop-with-2-4g)

**Comment by stereoDotLuigi** [comment]
I just opened a question/issue in Wireless-USB-OC-Big-Sur-Adapter.
Can you look at it? And yeah, I made my research.

**Comment by stereoDotLuigi** [comment]
Should I buy Archer T2U Plus or TL-WN725N?

**Comment by chris1111** [comment]
> Should I buy Archer T2U Plus or TL-WN725N?

T2U PLus working really well, Great Anthena on the adapter
