### ISSUE TITLE
I need kext for my RZ608 Wi-Fi 6E 80MHz wifi Adapet and BT 5.2

### ISSUE THREAD

**Issue by Sayor0630** [chris1111/D-LinkUtility-Package#24]
RZ608 Wi-Fi 6E 80MHz Is just a rebrand of MT7921K. Please I need it.

**Comment by chris1111** [comment]
And were you see MT7921K support here?

**Comment by Sayor0630** [comment]
> And were you see MT7921K support here?

Can you make one?
