### ISSUE TITLE
802.11 n WLAN Showing in Network tab but showing not connected and WiFi utility saying No Connection in macOS Sonoma

### ISSUE THREAD

**Issue by Sayor0630** [chris1111/D-LinkUtility-Package#26]
I installed this driver in macOS Sonoma. I have Wi-Fi Adapter with this device ID. 
![image](https://github.com/chris1111/D-LinkUtility-Package/assets/77576588/de05f5a2-9f29-43ec-8b6b-e3e3bf0a37cd)

It shows up in the Network tab of system settings. But says "Not Connected".
![image](https://github.com/chris1111/D-LinkUtility-Package/assets/77576588/50dd9784-2de3-4900-8b44-9e65521df656)

In the Wifi-Utility in this package, it also says "[No Connection!!!]"
![image](https://github.com/chris1111/D-LinkUtility-Package/assets/77576588/67e7f8fb-3b98-4013-9eb7-66648bbab3ff)

In case if you say that if I disabled SIP, I disabled it.
![image](https://github.com/chris1111/D-LinkUtility-Package/assets/77576588/c1e090bd-c3cb-465f-a194-95eeb64716ff)

Also I enabled the driver fom the Security of settings. I allowed it the restarted from there.

Note: A small note that any other drivers didn't even make my USB WI-Fi show up the the Network Tab at all. This driver made the USB Wi-Fi show up in the Network tab

**Comment by chris1111** [comment]
what is the adapter

**Comment by Sayor0630** [comment]
> what is the adapter

Maybe a RT2870 wifi card. it is a cheap USB wifi. It's Product ID is 0x7601. I really don't know the exact model of it. But it works on Windows.

**Comment by Sayor0630** [comment]
> what is the adapter

Maybe a RT2870 or 2770 wifi card. it is a cheap USB wifi. It's Product ID is 0x7601. I really don't know the exact model of it. But it works on Windows.

**Comment by chris1111** [comment]
Did you try this 


https://github.com/chris1111/D-LinkUtility-Package/blob/main/Troubleshooting.md

**Comment by Sayor0630** [comment]
> Did you try this
> 
> https://github.com/chris1111/D-LinkUtility-Package/blob/main/Troubleshooting.md

Is the Router name is the Wifi Name? and password is wifi password?

**Comment by Sayor0630** [comment]
> Did you try this
> 
> https://github.com/chris1111/D-LinkUtility-Package/blob/main/Troubleshooting.md

I did that and still no connection in Wifi utility

**Comment by Sayor0630** [comment]
> Did you try this
> 
> https://github.com/chris1111/D-LinkUtility-Package/blob/main/Troubleshooting.md

I did that and still no connection in Wifi utility

**Comment by Sayor0630** [comment]
> Did you try this
> 
> https://github.com/chris1111/D-LinkUtility-Package/blob/main/Troubleshooting.md

I did that and still no connection in Wifi utility
