### ISSUE TITLE
请问支持MTK 7603吗？

### ISSUE THREAD

**Issue by q-Mony** [chris1111/D-LinkUtility-Package#27]
我有一个USB 网卡，是360 3代的随身WiFi  使用的芯片应该是MTK的7603
https://bbs.360.cn/thread-5805711-1-1.html

**Comment by littlestar202** [comment]
MT7603U is not support by this App

**Comment by littlestar202** [comment]
> 我有一个USB 网卡，是360 3代的随身WiFi 使用的芯片应该是MTK的7603 https://bbs.360.cn/thread-5805711-1-1.html
MT7603U is not support by this App
