### ISSUE TITLE
Mt7921 support for macOS

### ISSUE THREAD

**Issue by pokewizardSAM** [chris1111/D-LinkUtility-Package#28]
Are yo planning to add support for this chipset, I know it's not possible rn but I would like to know the reason why is it that way, other mediated chipsets are supported so there has to be some way to make it run. thanks in advance

**Comment by chris1111** [comment]
There is no way for this to work because this chipset has no support for macOS, Mediatek stopped making USB drivers for macos since macOS 10.10 so we use an old drivers which still works and it is impossible without the source code of add other support
