### ISSUE TITLE
Unable to Connect

### ISSUE THREAD

**Issue by AcidRain9** [chris1111/D-LinkUtility-Package#3]
macOS 11.6 (20G165)
Here's my wireless USB details
Vendor ID : 0x0E8D (MediaTek Inc.)
Product ID : 0x7610
Friendly Name : 802.11ac Wireless LAN Card
MediaTek 802.11ac Wireless LAN Card - 2× WiFi

IORegistryExplorer:
![Screenshot 2021-10-02 at 9 00 48 PM](https://user-images.githubusercontent.com/26188786/135724280-cb8d5fd4-1ae3-4b45-84e3-2cf384fe20f5.png)

I'm always getting this [No connection]

![Screenshot 2021-10-02 at 9 15 30 PM](https://user-images.githubusercontent.com/26188786/135724442-813dec34-3a78-4d18-ad39-60970ceecde9.png)

I don't see anything happening to anything opening up when I try to execute AwakeDwa160UI or MiniTaskUSB-DWA160
![Screenshot 2021-10-02 at 9 23 04 PM](https://user-images.githubusercontent.com/26188786/135724723-b70d4094-64e6-4df9-8c4d-283df3f7787a.png)

Opening D-linkUtility via Terminal I get this 
![Screenshot 2021-10-02 at 9 27 17 PM](https://user-images.githubusercontent.com/26188786/135724831-a28ac5be-fdbf-44b0-8d70-e46538177b71.png)

same with DWA160
![Screenshot 2021-10-02 at 9 28 44 PM](https://user-images.githubusercontent.com/26188786/135724878-86f9bd2f-878a-4884-bbc1-0cd8efc93703.png)

LoginItem: 
![Screenshot 2021-10-02 at 9 29 48 PM](https://user-images.githubusercontent.com/26188786/135724912-775ce7ed-3310-432a-a703-7c50f4e7ca9f.png)

StartupParameters.plist
![Screenshot 2021-10-02 at 9 31 04 PM](https://user-images.githubusercontent.com/26188786/135724990-1dad28fb-ccea-44bc-bafe-658db5c34262.png)

I have uninstalled and installed the Utility many times but the same issue every time.

Any help will be appreciated

**Comment by chris1111** [comment]
What is the exacte brand of the USB wifi adapter and is the drivers using by thw card?

**Comment by AcidRain9** [comment]
It is a generic usb wifi card Aztech WL592USB 
https://cara96.blogspot.com/2017/04/aztech-wl592usb-wl592-usb-wireless.html
https://www.mediatek.com/products/broadbandWifi/mt7610u

I tried both first OpenCore It didn't work then I uninstalled it using the utility but then I installed it using / Library /Extensions

**Comment by chris1111** [comment]
It's a MTK7610U drivers it seems he is not supoort after El Capitan, I would like that it works for you but hey it's a shame

**Comment by AcidRain9** [comment]
It's alright, Thank you for your support

**Comment by AcidRain9** [comment]
OMG It's workingggg,  I installed the utility by selecting OpenCore and before rebooting I replaced the RT2870USBWirelessDriver.kext in the kexts with the kext found in https://www.mediatek.com/products/broadbandWifi/mt7610u and then rebooted and it's workinngggg 
![Screenshot 2021-10-03 at 5 42 36 AM](https://user-images.githubusercontent.com/26188786/135735526-ec74c5b4-68d4-45c4-bcf8-20e988535d0b.png)

Thank you sooo much

**Comment by AcidRain9** [comment]
One last question how can I remove the signal strength in the statusbar it's kinda distracting and nothing happens when I click on Wireless Preference
