### ISSUE TITLE
Stuck on no connection

### ISSUE THREAD

**Issue by vxibrahim** [chris1111/D-LinkUtility-Package#31]
Hello, could you provide some insight on what I've done wrong?

I'm on opencore, my wifi adapter is RALINK MT7601u Wireless Adapter. I'm on MacOS Monterey.

I have trouble shooted and put the correct mac address, wifi and password. However, it still shows up as 'No connection!!'.

I can confirm the adapter is working as the app does not reach the No connection part if adapter is not plugged in. The kext is present in the kext folder and config.plist is also updated.

Thank you.

**Comment by chris1111** [comment]
I know it's sad but it's not supported, there's only `MT7601`
here is the list of supported [drivers](https://github.com/chris1111/D-LinkUtility-Package?tab=readme-ov-file#support-drivers)

`MT7601`, MT7610, RT5370, RT2870, RT3071, RT2770, RT5572, RT3572, RT3072, RT3070, RT3573, MT7621U

Do you please show me the same picture here of USB when the adapter is plugin
Whit your infos I try to add the drivers ID

![Screenshot 2024-08-06 at 6 19 26 AM](https://github.com/user-attachments/assets/8a1551fc-9804-469a-bc6e-b9b80f78ddee)

**Comment by vxibrahim** [comment]
Oh:( I thought MT7601 and MT7601u were the same thing. My apologies.

![image](https://github.com/user-attachments/assets/c7af3fc8-3181-4084-8b7e-014bfa62c913)

Heres the image you asked for.

I'm out of luck I guess, i'm running a hackintosh and my native wifi card (DW1705) and now wifi adapter are both unsupported lol.

**Comment by chris1111** [comment]
Did you try USB 2 adapter?

**Comment by vxibrahim** [comment]
> Did you try USB 2 adapter?

Usb 2 adapter? I'm sorry i'm not sure what you mean

**Comment by chris1111** [comment]
> > Did you try USB 2 adapter?
> 
> Usb 2 adapter? I'm sorry i'm not sure what you mean

I mean if your laptop have only USB 3 port try using USB 2 HUB

**Comment by vxibrahim** [comment]
> > > Did you try USB 2 adapter?
> > 
> > Usb 2 adapter? I'm sorry i'm not sure what you mean
> 
> I mean if your laptop have only USB 3 port try using USB 2 HUB

I have tried that, does not work :[

**Comment by vxibrahim** [comment]
Should I close the issue?
