### ISSUE TITLE
A Question About MT7601U

### ISSUE THREAD

**Issue by POORIANSARI** [chris1111/D-LinkUtility-Package#33]
Hell dear Chris1111

I have a Wifi Dongle with Model WN727N v4 that uses MT7601U chipset. I have tested All of your kexts & it is not working.
I was Wondering if I can Ask you there is any solution on this?

Notice:
I bought this dongle for my Hackintosh years ago in Yosemite era.

Thanks.

**Comment by chris1111** [comment]
Did you try this [Wireless-USB-OC-Big-Sur-Adapter](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter) with OpenCore bootloader

**Comment by POORIANSARI** [comment]
Unfortunately no it is not working and you mentioned it does not support
mediatek.there is a 32 bit kext on the tplink website that worked years ago
and i have no idea how to make a kext
