### ISSUE TITLE
Mediatek MT7921K Compatibility ?

### ISSUE THREAD

**Issue by Darkpulse47** [chris1111/D-LinkUtility-Package#8]
Hi there !

I would like to know if there is any hope to make it work the new combo Wifi + BlueTooth card embeded on my motherboard Gigabyte X570S PRO AX.
Looks like it is the MediaTek MT7921K.

Sorry if I post that in the wrong section but I'm pretty new on Github.

Thanks for your feedback.

**Comment by chris1111** [comment]
[It support ](http://en.techinfodepot.shoutwiki.com/wiki/MediaTek_MT7921K_Reference_Design)only in Linux and Windows
